### ISSUE TITLE
Add descriptive README.md

### ISSUE THREAD

**Issue by LeoCode0** [LeoCode0/PlatziChallenge--twitter-profile#5]

**Comment by julianf-dev** [comment]
# PlatziChallenge--twitter-profile

An example of twitter's profile page

### Instalación 🔧

open index.html

## Construido con 🛠️

- Love
- HTML
- CSS

## Contribuyendo 🖇️

Cualquier contirbución al proyecto es bien recibida !

## Autor ✒️

- Comunidad Platzi and LeoCode

## Licencia 📄


---

**Comment by LeoCode0** [comment]
Excelente! Lo único que haría falta sería hacer el Pull request con los cambios de este readme y quedaría dentro del repo :D
